name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.25'

      - name: Build and Deploy book
        run: |
          chmod +x build.sh
          ./build.sh
      - name: Deploy to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
